qtbase: Autospec creation for update from version 5.12.1 to version 5.12.2
Albert Astals Cid (2):
      png: initialize color_type to 0
      Initialize bit_depth

Alexander Volkov (2):
      xcb: Avoid repaint lags with DnD
      Improve keyboard navigation in QListView when isWrapping is enabled

Allan Sandfeld Jensen (7):
      Fix resolve() on fonts returned from QWidget::font()
      Fix building offscreen QPA with Qt XCB
      Avoid picking worse formats when matching compatible formats
      Fix regression in QPlainTextEdit updating
      Fix merge mistake in 'Avoid picking worse formats when ...'
      Avoid creating wide images with negative bytesPerLine
      Blacklist nouveau and llvmpipe for multithreading

Andre de la Rocha (4):
      Windows QPA: Cache "forcedScreenForGLWindow" to avoid overhead
      Windows QPA: handle pointer messages received during a drag and drop
      Fix QSpinBox tests failing after change in the Windows QPA
      Windows QPA: Handle mouse input using legacy messages

Andreas Hartmetz (1):
      QMetaObject::Connection overview documentation improvements

André Klitzing (2):
      Update bundled libpng to version 1.6.36
      Fix session resumption with OpenSSL 1.1

Andy Shaw (6):
      Don't enable the input method for the QListView in a QInputDialog
      Android: If there is no surrounding text then don't try to delete it
      qmake: Add variables for setting the version number and name in Android
      Windows: Freetype: Load fonts from the user locations
      Android: Add support for getting the UiLanguages
      Fix a couple of SQL tests

Antti Kokko (1):
      Add changes file for Qt 5.12.2

BogDan Vatra (3):
      Remove "/data/local/tmp/qt/" support
      Android: follow official android flags for cmake
      Load main library as soon as possible

Boubacar DIENE (1):
      Fix "error: too many arguments to function media_get_entity_by_name()"

Christian Ehrlicher (11):
      QSqlRelationalDelegate: compile with QT_NO_CAST_FROM_BYTEARRAY
      tst_QString: fix localeAwareCompare() when using ICU
      tst_QPrinter: stabilize qprinter test
      tst_QGraphicsItem: stabilize cursor() test
      QAbstractItemView: fix rendering centered/right aligned item text
      tst_QItemDelegate: try to stabilize combobox test
      QPictureIO::read(): don't work on dangling pointer
      tst_QHeaderView: fix defaultSectionSizeTest() on High-DPI screens
      QMenuItem: fix rendering with css styling
      QCommonStyle: factor out elided text calculation
      QToolButton: fix handling multi-line texts

Christian Kandeler (2):
      androiddeployqt: Do not check for stdcpp-path in auxiliary mode
      Automatic resources: Fix tooling support

David Edmundson (1):
      Fixups for GL_CONTEXT_LOST in QOpenGLExtensionMatcher

David Faure (1):
      QLocale: fix crash when using qDebug() in a global destructor

Dmitry Sokolov (2):
      Kludge popen/pclose calls on MS-Win
      Inline expression to bypass compiler bug

Edward Welbourne (9):
      Fix alignment-warnings about Q_DECLARE_PRIVATE's casts
      Eliminate some stray misleading paths from expected output files
      Use RAII to handle setting of default locale in tst_QString
      generate_expected_output.py: placate FutureWarning from python
      Q(Date|Time)+::toString: correct account of format specifiers
      Add some missing expected_*.tap files for the testlib selftest
      Add testlib selftests for double and for non-finite float and double
      Avoid read-outside-array error by QStringRef over-reach
      Recognize UNC paths as absolute (i.e. not relative)

Eirik Aavitsland (4):
      Fix xbm image format handler: properly reject invalid files
      Painter path stroking: fix capping of beziers ending in tight turns
      Fix QColor::toCmyk() for rgb(0, 0, 0)
      Doc: decrease confusion about HSV vs HSL in QColor

Elena Zaretskaya (1):
      Ability to switch language under platform eglfs/linuxfb

Eric Lemanissier (2):
      configure: handle FREETYPE_* variables
      configure: use proper separator for mingw libraries

Eskil Abrahamsen Blomfeldt (3):
      Fix default font properties when using raw fonts for text layouts
      Update bundled Freetype to 2.9.1
      Don't wrongly detect fonts as oblique

Friedemann Kleint (10):
      QSplashScreen: Fix positioning in multimonitor setups
      Documentation: Add \nullptr macro and use where applicable
      Fix multiple emission of QGuiApplication::lastWindowClosed() when native child widgets are used
      Windows QPA: Use member initialization in struct WindowCreationData
      Windows QPA: Fix tray icon becoming visible before show
      Windows QPA: Move the code installing the filter for WM_TASKBARCREATED
      QColorDialog: Remove flag Qt::MSWindowsFixedSizeDialogHint
      Add doc note about Qt::MSWindowsFixedSizeDialogHint and High DPI
      Windows/Direct2d QPA: Use nullptr
      Fix QSplashscreen positioning on Android

Gatis Paeglis (3):
      configure: fix a bug where -no-xcb implied eglfs_x11=no
      eglfs_kms: Fix build with -no-opengl
      xcb: check for nullptr when reading AT_SPI_BUS property

Heikki Halmet (1):
      Make Android arch x86_64 to use platform-21

Jesus Fernandez (2):
      Fix unused parameters
      Replace executedQuery when executing a new query

Joerg Bornemann (16):
      Add the command line option --no-strip to androiddeployqt
      Consume the -skip option in qtbase/configure
      configure: Respect -continue in qtConfParseCommandLine
      Make the Makefile a dependency of default targets for nmake
      Normalize some SIGNAL/SLOT signatures
      Fix install targets for generated private headers
      Fix determination of OpenGL include paths on macOS
      Fix warning in tst_qopengl.cpp
      qmake/vcxproj generator: Fix bug in extra compiler initialization
      INSTALL: Remove outdated reference to Windows CE
      qmake vcxproj generator: Update platform toolset and solution header for VS 2019
      Turn bcm_host library into makeSpec source
      Fix OpenGL ES2 build on Linux
      Revert "Fix determination of OpenGL include paths on macOS"
      Add cmdline feature to qmake
      Add all library dependencies for static OpenSSL builds on Windows

Joni Poikelin (1):
      Prevent QPixmap::load from touching QPixmapCache in non-gui threads

Juha Karjalainen (1):
      Fix blacklisting tst_QTimer::basic_chrono()

Kai Koehne (10):
      Fix typo in fontconfig autotest
      QtOpenGLExtensions: Unify license headers
      Doc: End sentence about Q_GADGET with dot
      Fix license header for qprinterinfo.cpp
      Avoid test failures in tst_qtimezone.cpp and Windows 10 1809
      QtGui: Unify license headers
      QtConcurrent: Unify license headers
      QtOpenGL: Unify license headers
      QTextDocument: Do respect white-space:nowrap
      Emit returnPressed() signal for the lineEdit embedded in QDateTimeEdit

Kari Oikarinen (3):
      Bump version
      Blacklist tst_QGraphicsItem::cursor on WinRT
      QWizard: Correctly calculate watermark size hint

Lars Knoll (3):
      Fix QTextTable:insertRows() for tables with spanning cells
      Fix an assertion in the BiDi algorithm
      Fix two smaller bugs in the BiDi engine

Lars Schmertmann (2):
      Reorder the elements of the Android manifest to fix a lint warning
      Add a string to the Android manifest to fix a lint warning

Laszlo Agocs (1):
      eglfs: avoid breaking builds without EGL_EXT_platform_base

Liang Qi (1):
      tests: require widgets explicitly

Lorn Potter (3):
      wasm: fix blob download handling
      wasm: remove BINARYEN_METHOD from link line
      wasm: fix building examples and applications

Martin Storsjö (1):
      qsimd: Fix compilation with trunk clang for mingw

Michael Brasser (1):
      Update QOpenGLTexture::generateMipMaps for ES 3

Mikhail Svetkin (1):
      qtlite: Fix build libs with -no-feature-regularexpression

Mitch Curtis (2):
      Doc: mention that some filtered events need to be explicitly accepted
      Fix crash when using Qt Virtual Keyboard with QCalendarWidget

Morten Johan Sørvig (4):
      Wasm: disable resources_big
      Cocoa: Don?t cache accessibility role
      Wasm: remove debug output.
      Fix QDeadlineTimer::Forever case in QWaitCondition

Mårten Nordheim (4):
      QSyntaxHighlighter: cancel delayed highlight if done manually
      tst_qsyntaxhighlighter: fix no-op QTRY_VERIFY check
      clang-cl: use GCC -m CPU feature flag option
      qfilesystemengine_win: Update LinkType whenever asked

Nico Vertriest (2):
      Doc: Complete doc on QHostAddress::clear()
      Doc: Correct minor link issue in qwidget.cpp

Oliver Wolff (11):
      qmltestcase: Fix generation of Visual Studio project files
      testlib: Add missing header files to .pro file
      testlib: Add BXPASS and BXFAIL
      winrt: Use ES3 ANGLE code path when blitting widgets
      Revert "winrt: Skip context validation in ANGLE"
      windows: Support OpenGL ES versions > 3.0 with ANGLE
      winrt: Warn if OpenGL ES version is set to a value > 3.0
      winrt qpa: Remove last windows phone leftovers
      Add support for Visual Studio 2019
      qmake vcxproj generator: Use correct version in solution header for 2017
      winrt: Handle WaitForWindowExposed

Oswald Buddenhagen (2):
      fix out-of-bounds access on trailing percent sign in tr() argument
      qmake: don't mess up linking order of frameworks

Roland Rossgotterer (2):
      Always access the 64-bit registry key to read MachineGuid
      Increase sysctl argument buffer size to include null character

Rolf Eike Beer (2):
      fix crash if no screens are available
      qtbearer networkmanager: fix whitespace

Samuel Gaist (1):
      Fix QMacStyle QPalette warning

Samuel Thibault (1):
      Add <features.h> include to hurd-g++ mkspec

Thiago Macieira (3):
      Fix change-of-sign warnings in ICC 19
      Fix race condition in getting the system locale data
      x86: Disable AVX support on 64-bit MinGW

Thomas Miller (1):
      Add arm64 winrt target

Timur Pocheptsov (9):
      QNetworkReplyHttpImpl::_q_startOperation - remove a useless warning
      Emit paletteChanged and send ApplicationPaletteChange on theme change
      QMacStyle - take into account that native controls are transparent now
      tst_qsslsocket - blacklist several test temporarily
      QMacStyle: fix PE_PanelLineEdit and PE_FrameLineEdit handling
      SecureTransport: do not set max protocol version
      QMacStyle - fix a weird NSBox geometry
      http2: skip content-length for content-encoding: gzip/deflate
      Make tst_QUdpSocket::lincLocalIPv6 less sadistic

Tony Sarajärvi (3):
      Blacklist a flaky qtableview function in WinRT
      Expand blacklisting of qthreadpool to cover linux distros
      Blacklist qtimer/basic_chrono on macos due to flakiness

Tor Arne Vestbø (31):
      qWaitFor: Prevent being stuck in QCoreApplication::processEvents
      macOS: Use tool environment to ensure tests load matching Qt libraries
      Fix default rpath dirs on Apple platforms
      Use requestUpdate instead of timer in a few GL examples
      Always unlock graphics buffer after binding texture during composeAndFlush
      testlib: Format durations using C locale
      Remove requirement to lock graphics buffer before getting total size
      macOS: Don't check for stale SDK unless target needs to be remade
      macOS: Apply alpha channel to surface format even when non-default
      macOS: Don't deliver update requests for windows that need display
      harbuzzng: Remove assumption about Core Text working in 96 DPI
      macOS: Explain QNSViewMouseMoveHelper for future generations
      macOS: Simplify mouse tracking
      macOS: Treat default swapInterval (-1) as vsync-enabled display-link
      macOS: Don't send redundant geometry change events for top level windows
      Widgets: Only set WA_WState_ExplicitShowHide via public API
      Don't allow backingstore flush to non-raster surfaces
      macOS: Add explicit auto-release pool for requestActivateWindow
      Add developer documentation on how to debug missing auto-release pools
      macOS: Don't rely on QGuiApplication::instance() during CVDisplayLink callback
      macOS: Remove screen-update disable during resize
      macOS: Add auto-release pool during QCocoaScreen::deliverUpdateRequests()
      Track call sites of QMacAutoReleasePools for debugging pool usage
      QBackingStore: Make QPlatformBackingStore creation lazy
      macOS: Remove dead code in window activation handling
      macOS: Simplify QCocoaWindow::setVisible
      macOS: Modernize worksWhenModal handling
      macOS: Remove redundant tracking of modal sessions in QCocoaWindow
      macOS: Implement QNSWindow/QNSPanel mixin using preprocessor includes
      macOS: Set up platform window reference before initializing QNSWindow/Panel
      macOS: Remove special handling for hiding tool windows on application hide

Ulf Hermann (2):
      Windows: Set opengl swap interval whenever we make a new window current
      Document that you shouldn't Q_ENUM() things outside the int range

Volker Hilsheimer (1):
      Include relevant example code in documentation of setUrlHandler

Vyacheslav Koscheev (1):
      Android: fix NPE on m_editPopupMenu

Yuhang Zhao (6):
      qtmain_win.cpp: Replace NULL with nullptr
      qtmain_win.cpp: Improve coding style
      qtmain_win.cpp: Remove unused header files
      Win32 makefile for qmake: Use proper linker
      Fix compilation with icc, converting between egl's and gl's Error types
      qmake: Optimize for speed instead of size